name: "Release packages"

on:
  release:
    types:
      - published

env:
  SLN: "./src/DandyStrategies.slnx"
  DOTNET_VERSION: "10.0.x"
  PACK_OUTPUT_DIRECTORY: "${{ github.workspace }}/output"
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
  NUGET_SOURCE_URL: "https://api.nuget.org/v3/index.json"

jobs:
  publish:
    name: "Pack and publish packages"
    runs-on: "ubuntu-latest"
    steps:
    - name: "Checkout"
      uses: "actions/checkout@v4"
      with:
        fetch-depth: 0

    - name: "Setup .NET"
      uses: "actions/setup-dotnet@v4"
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: "Restore dependencies"
      run: "dotnet restore ${{ env.SLN }}"

    - name: "Build project"
      run: "dotnet build ${{ env.SLN }} --no-restore --configuration Release"

    - name: "Pack project"
      run: |
        VERSION=${{ github.ref_name }}
        VERSION=${VERSION#v}  # Remove 'v' prefix
        dotnet pack ${{ env.SLN }} --no-restore --no-build --configuration Release --include-symbols -p:PackageVersion=$VERSION --output ${{ env.PACK_OUTPUT_DIRECTORY }}

    - name: "Push package"
      run: "dotnet nuget push '${{ env.PACK_OUTPUT_DIRECTORY }}/*.nupkg' -k ${{ env.NUGET_API_KEY }} -s ${{ env.NUGET_SOURCE_URL }} --skip-duplicate"